baseurl = "https://www.viveknidhi.com"
theme = "hugo-geo-theme"
relativeURLs = false
languageCode = "en-gb"
title = "Vivek Nidhi"
disqusShortname = "shortcode-here"
paginate = 5

[taxonomies]
	tag = "tags"
	tutorial = "tutorials"

[params]
	showglobe = true

	favicon = "favicon.ico"
	
	analytics = "code-here"

	email = "vivek.nidhi@gmail.com"

	profilepic = "img/profile.png"
	
	title = "Vivek Nidhi"
	subtitle = "My Personal Site"

	# Social buttons for sidebar
	# Each of these are optional
	[[params.socialbuttons]]
	faicon = "github"
	url = "https://github.com/viveknidhi"
	[[params.socialbuttons]]
	faicon = "twitter"
	url = "https://twitter.com/viveknidhi"
	[[params.socialbuttons]]
	faicon = "linkedin"
	url = "https://www.linkedin.com/in/cloudtechie/"
	[[params.socialbuttons]]
	
	[[params.navlinks]]
	name = "About"
	url = "/about"
	
	[[params.navlinks]]
	name = "Travel"
	url = "/travel"

    [[params.navlinks]]
	name = "Tech"
	url = "tech/"
	
	[[params.navlinks]]
	name = "Contact"
	url = "contact/"
scripts = [
"//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.8.0/languages/go.min.js",
]

css = [
"//cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css"
]